FROM debian:bullseye

# Install our packages and setup the stage user.
#
# The useradd line in this next section needs a '-l' to workaround a hang 
# caused by large UIDs (https://github.com/moby/moby/issues/5419).
#
ARG USER=stage
ARG UID=499
ARG GID=499
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update                                                             \
    && apt-get install -y --no-install-recommends                              \
        git lldb gdb curl clang xz-utils sudo make vim pip mariadb-client      \
        pkg-config openssl libssl-dev libxml2-dev                              \
    && apt-get clean && rm -rf /var/lib/apt/lists/*                            \
    && pip --no-cache-dir install wasmtime                                     \
    \
    && groupadd --gid $GID $USER                                               \
    && useradd -l --create-home --uid $UID --gid $GID --shell /bin/bash $USER  \
    && echo 'ALL ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Install the WASI SDK and Wasmtime.
#
COPY docker/*.sh /tmp/library-scripts/
RUN bash /tmp/library-scripts/install-wasi-sdk.sh
RUN bash /tmp/library-scripts/install-wasmtime.sh

# Now switch to the user staging account and install the rest.
#
USER ${UID}:${GID}
WORKDIR /home/${USER}
ENV PATH="/home/${USER}/.cargo/bin:${PATH}"

# Install the Rust toolchain, targets, useful components, tools, and wit-bindgen.
#
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y    \
    && bash /tmp/library-scripts/install-rust-tools.sh                         \
    && bash /tmp/library-scripts/install-wit-bindgen.sh

# Clone and build SingleStore tools -- `pushwasm` and `writ`.
# Make sure to clean up the cargo cache when we're done.
#
RUN git clone --depth 1 https://github.com/singlestore-labs/pushwasm.git       \
    && mkdir -p bin                                                            \
    && cd pushwasm                                                             \
    && cargo build --release                                                   \
    && cp target/release/pushwasm ../bin                                       \
    && cd ..                                                                   \
    && rm -rf pushwasm                                                         \
    \
    && git clone --depth 1 https://github.com/singlestore-labs/writ.git        \
    && mkdir -p bin                                                            \
    && cd bin                                                                  \
    && ln -s ../writ/bin/writ writ                                             \
    && cd ..                                                                   \
    \
    && cargo cache -r all

# Hacks and stuff.
#
RUN echo "set mouse=r" >> ~/.vimrc                                             \
    && echo 'export PS1="\[\033[0;34m\][\[\033[1;34m\]dev-shell\[\033[0;34m\]]:\[\033[0;35m\]\w\[\033[1;35m\] % \[\033[0m\]"' \
        >> ~/.bashrc                                                           \
    && echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc

