# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.234.0/containers/python-3/.devcontainer/base.Dockerfile

# [Choice] Python version (use -bullseye variants on local arm64/Apple Silicon): 3, 3.10, 3.9, 3.8, 3.7, 3.6, 3-bullseye, 3.10-bullseye, 3.9-bullseye, 3.8-bullseye, 3.7-bullseye, 3.6-bullseye, 3-buster, 3.10-buster, 3.9-buster, 3.8-buster, 3.7-buster, 3.6-buster
ARG VARIANT="3.10-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

# Configuration
#
ARG NODE_VERSION="16"

ENV RUST_INSTALL_SCRIPT_VERSION=v0.238.0
ENV CARGO_HOME=/usr/local/cargo \
    RUSTUP_HOME=/usr/local/rustup
ENV PATH=${WASI_SDK_HOME}/bin:${CARGO_HOME}/bin:${PATH}

# Install additional OS packages and Node
#
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive                    \
    && apt-get -y install --no-install-recommends mariadb-client               \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*                         \
    && bash -c                                                                 \
        "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/${RUST_INSTALL_SCRIPT_VERSION}/script-library/rust-debian.sh")" \
        -- "${CARGO_HOME}" "${RUSTUP_HOME}"                                    \
    \
    && if [ "${NODE_VERSION}" != "none" ]; then                                \
        su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi \
    \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /usr/local/cargo/git \
    && mkdir -p /usr/local/cargo/registry \
    && chmod g+w /usr/local/cargo/git \
    && chmod g+w /usr/local/cargo/registry

# Install the WASI SDK and Wasmtime.
#
COPY docker/*.sh /tmp/library-scripts/
RUN bash /tmp/library-scripts/install-wasi-sdk.sh
RUN bash /tmp/library-scripts/install-wasmtime.sh

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1

# User-specific code after this point.
#
USER vscode
WORKDIR /home/vscode

# Setup python deps and configure rust.
#
RUN pip3 --disable-pip-version-check --no-cache-dir install mypy wasmtime      \
    && rm -rf /tmp/pip-tmp                                                     \
    && bash /tmp/library-scripts/install-rust-tools.sh                         \
    && bash /tmp/library-scripts/install-wit-bindgen.sh

# Clone and build SingleStore tools -- `pushwasm` and `writ`.
#
RUN git clone https://github.com/singlestore-labs/pushwasm.git                 \
    && mkdir -p bin                                                            \
    && cd pushwasm                                                             \
    && cargo build --release                                                   \
    && cp target/release/pushwasm ../bin                                       \
    && cd ..                                                                   \
    && rm -rf pushwasm                                                         \
    \
    && git clone https://github.com/singlestore-labs/writ.git                  \
    && mkdir -p bin                                                            \
    && cd bin                                                                  \
    && ln -s ../writ/bin/writ writ                                             \
    && cd ..                                                                   \
    && cargo cache -r all
