[package]
name = "unicode_normalizer"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "60e3c5b41e616fee239304d92128e117dd9be0a7" }
unicode-normalization = "0.1.22"

[lib]
crate-type = ["cdylib"]
