#!/usr/bin/env bash
set -eu

FILE_TO_DEBUG="${1}"

TARGET_DIR=$(cargo metadata --format-version 1 | jq -r '.target_directory')
CRATE_NAME=$(cargo get --name --root "${FILE_TO_DEBUG}")
CRATE_DIR=$(cargo workspaces list --json | jq -r ".[] | select(.name == \"${CRATE_NAME}\") | .location")

WASM_PATH="${TARGET_DIR}/wasm32-wasi/debug/${CRATE_NAME}.wasm"
# currently unused
WIT_PATH="${CRATE_DIR}/${CRATE_NAME}.wit"

${TARGET_DIR}/debug/debugger 3000 "${WASM_PATH}"